spring:
  application:
    name: tlias-web-management
# mysql配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # windows
    url: jdbc:mysql://localhost:3306/tlias
    # linux
#    url: jdbc:mysql://192.168.100.128:3306/tlias
    # docker
#    url: jdbc:mysql://mysql:3306/tlias
    username: root
    password: 1301041221zxc
# 上传大文件
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

# mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 驼峰命名
    map-underscore-to-camel-case: true

# 分页合理化(避免页码为-1)
pagehelper:
  reasonable: true
  helper-dialect: mysql

# spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

# 阿里云oss配置
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: java-study-ai
    region: cn-beijing
